---

- name: Ensure dependencies are installed.
  become: yes
  apt:
    name:
      - curl
      - apt-transport-https
      - default-jre-headless
      - openjdk-8-jre-headless
    state: installed

- name: Add Jenkins apt repository key.
  become: yes
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: Add Jenkins apt repository.
  become: yes
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes

- name: Install Jenkins
  become: yes
  apt:
    name:
      - jenkins
    state: installed