---

- hosts: int
  gather_facts: false
  become: yes
  vars:
    - name_container: "crafter"
    - network_name: "lxdbr0"
    - ipv4_network: "10.0.82.1"
    - ipv4_container: "10.0.82.6"
    - ssh_user: "ansible"
    - ssh_password: "ansible"
    - ssh_port: "2206"
    - iptables_interface: "eth1"
    - host_http_port: "8083"
    - container_http_port: "8080"
  roles:
    - python_minimal
    - create_container
