---
- hosts: int
  remote_user: vagrant
  gather_facts: false
  become: yes
  roles:
    - python_minimal
    - lxd
    - iptables_conf

- include: jenkins.yml

- include: nexus.yml

- include: sonarqube.yml